[package]
name = "cat_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
termcolor = "1.4.1"
uwuify = { git = "https://github.com/RegenJacob/uwu/" }

[package.metadata.cargo-machete]
ignored = ["uwuify"]

